FUNCTION_REPORT_QUESTIONS = [
    {
        "key": "function_name",
        "target": "function_report",
        "icon": "👤",
        "question": "What is your full name?",
        "helper": "Enter the name of the disabled person.",
        "type": "text",
    },
    {
        "key": "function_ssn",
        "target": "function_report",
        "icon": "🔢",
        "question": "What is your Social Security number?",
        "helper": "You can leave this blank and add it later if needed.",
        "type": "text",
    },
    {
        "key": "function_phone",
        "target": "function_report",
        "icon": "📞",
        "question": "What daytime phone number can Social Security use to reach you?",
        "helper": "Include area code. If none, write None.",
        "type": "text",
    },
        {
        "key": "living_place",
        "target": "function_report",
        "icon": "🏠",
        "question": "Where do you live?",
        "helper": "Choose the closest option.",
        "type": "select",
        "options": [
            "", "House", "Apartment", "Boarding House",
            "Nursing Home", "Shelter", "Group Home", "Other"
        ],
    },
    {
        "key": "living_place_other",
        "target": "function_report",
        "icon": "🏠",
        "question": "You selected Other. Please describe where you live.",
        "helper": "Example: motel, transitional housing, staying with someone temporarily, or another living situation.",
        "type": "text",
        "depends_on": {
            "key": "living_place",
            "value": "Other"
        },
    },
    {
        "key": "living_with",
        "target": "function_report",
        "icon": "👥",
        "question": "Who do you live with?",
        "helper": "Choose the closest option.",
        "type": "select",
        "options": [
            "", "Alone", "With Family", "With Friends", "Other"
        ],
    },

    {
        "key": "living_with_other",
        "target": "function_report",
        "icon": "👥",
        "question": "You selected Other. Please describe who you live with.",
        "helper": "Example: roommate, caregiver, friend, temporary housing, or another arrangement.",
        "type": "text",
        "depends_on": {
            "key": "living_with",
            "value": "Other"
    },
    },
        
    {
        
        "key": "condition_limits_work",
        "target": "function_report",
        "icon": "🩺",
        "question": "How do your illnesses, injuries, or conditions limit your ability to work?",
        "helper": "Describe how your conditions affect work tasks, attendance, pain, focus, movement, or stamina.",
        "type": "textarea",
        "check_type": "condition_limits_work",

    },
    {
        
        "key": "daily_routine",
        "target": "function_report",
        "icon": "🌅",
        "question": "What do you do from the time you wake up until going to bed?",
        "helper": "Describe a typical day. Include meals, chores, rest breaks, help from others, and activities you avoid.",
        "type": "textarea",
        "check_type": "daily_routine",

    },
    {
        "key": "care_for_others",
        "target": "function_report",
        "icon": "🤝",
        "question": "Do you take care of anyone else?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
        
    },
    {
        "key": "care_for_others_details",
        "target": "function_report",
        "icon": "🤝",
        "question": "Who do you care for, and what do you do for them?",
        "helper": "Only answer this if you said Yes.",
        "type": "textarea",
        "depends_on": {"key": "care_for_others", "value": "Yes"},
        "check_type": "care_for_others",
    },
    {
        "key": "care_for_pets",
        "target": "function_report",
        "icon": "🐾",
        "question": "Do you take care of pets or other animals?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "care_for_pets_details",
        "target": "function_report",
        "icon": "🐾",
        "question": "What do you do for the pets or animals?",
        "helper": "Only answer this if you said Yes.",
        "type": "textarea",
        "depends_on": {"key": "care_for_pets", "value": "Yes"},
        "check_type": "care_for_pets",
    },
    {
        "key": "help_care_others_animals",
        "target": "function_report",
        "icon": "🧑‍🤝‍🧑",
        "question": "Does anyone help you care for other people or animals?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "help_care_others_animals_details",
        "target": "function_report",
        "icon": "🧑‍🤝‍🧑",
        "question": "Who helps, and what do they do to help?",
        "helper": "Only answer this if you said Yes.",
        "type": "textarea",
        "depends_on": {"key": "help_care_others_animals", "value": "Yes"},
        "check_type": "care_help",
    },
    {
        "key": "before_conditions",
        "target": "function_report",
        "icon": "🔙",
        "question": "What could you do before your conditions that you cannot do now?",
        "helper": "Examples: work, lift, stand, drive, cook, clean, shop, socialize, concentrate.",
        "type": "textarea",
        "check_type": "before_conditions",
    },
    {
        "key": "sleep_affected",
        "target": "function_report",
        "icon": "🌙",
        "question": "Do your conditions affect your sleep?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "sleep_affected_details",
        "target": "function_report",
        "icon": "🌙",
        "question": "How do your conditions affect your sleep?",
        "helper": "Examples: pain wakes you up, trouble falling asleep, medication side effects, nightmares, or needing naps.",
        "type": "textarea",
        "depends_on": {"key": "sleep_affected", "value": "Yes"},
        "check_type": "sleep_affected",
    },
        {
        "key": "personal_care",
        "target": "function_report",
        "icon": "🛁",
        "question": "Do your conditions affect your personal care?",
        "helper": "Examples: dressing, bathing, hair care, shaving, feeding yourself, using the toilet, or write No problem.",
        "type": "textarea",
        "check_type": "personal_care",
    },
    {
        "key": "needs_grooming_reminders",
        "target": "function_report",
        "icon": "⏰",
        "question": "Do you need reminders for personal care or grooming?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "grooming_reminders_details",
        "target": "function_report",
        "icon": "⏰",
        "question": "What reminders or help do you need for personal care or grooming?",
        "helper": "Examples: reminders to shower, brush teeth, change clothes, or comb hair.",
        "type": "textarea",
        "depends_on": {"key": "needs_grooming_reminders", "value": "Yes"},
        "check_type": "personal_care",
    },
    {
        "key": "needs_medicine_reminders",
        "target": "function_report",
        "icon": "💊",
        "question": "Do you need help or reminders taking medicine?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "medicine_reminders_details",
        "target": "function_report",
        "icon": "💊",
        "question": "What help do you need with medicine?",
        "helper": "Examples: reminders, pill organizer, someone handing you medicine, or help tracking doses.",
        "type": "textarea",
        "depends_on": {"key": "needs_medicine_reminders", "value": "Yes"},
        "check_type": "medication_side_effects",
    },
    {
        "key": "prepare_meals",
        "target": "function_report",
        "icon": "🍳",
        "question": "Do you prepare your own meals?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "meal_preparation_details",
        "target": "function_report",
        "icon": "🍽️",
        "question": "What meals do you prepare, how often, and how long does it take?",
        "helper": "Examples: sandwiches, frozen meals, simple meals, daily, weekly, 10 minutes, 30 minutes.",
        "type": "textarea",
        "depends_on": {"key": "prepare_meals", "value": "Yes"},
        "check_type": "meal_preparation",
    },
    {
        "key": "meal_changes",
        "target": "function_report",
        "icon": "🍴",
        "question": "Have your cooking habits changed since your conditions began?",
        "helper": "Examples: cook less often, need help, use microwave more, avoid stove, take longer, or write None.",
        "type": "textarea",
        "check_type": "meal_preparation",
    },
    {
        "key": "housework",
        "target": "function_report",
        "icon": "🧹",
        "question": "What housework or yard work can you do?",
        "helper": "Examples: dishes, laundry, sweeping, vacuuming, mowing, cleaning, taking trash out, or None.",
        "type": "textarea",
        "check_type": "housework",
    },
    {
        "key": "housework_time_frequency",
        "target": "function_report",
        "icon": "📆",
        "question": "How often do you do housework or yard work, and how long does it take?",
        "helper": "Example: laundry once a week for 30 minutes, dishes daily for 10 minutes, or None.",
        "type": "textarea",
        "check_type": "housework",
    },
    {
        "key": "housework_help",
        "target": "function_report",
        "icon": "🤝",
        "question": "Do you need help or encouragement doing housework or yard work?",
        "helper": "Describe the help needed, or write None.",
        "type": "textarea",
        "check_type": "housework",
    },
    {
        "key": "go_outside",
        "target": "function_report",
        "icon": "🚪",
        "question": "How often do you go outside?",
        "helper": "Examples: every day, a few times a week, only for appointments, or rarely.",
        "type": "text",
        "check_type": "getting_around",
    },
    {
        "key": "travel_alone",
        "target": "function_report",
        "icon": "🚶",
        "question": "Can you go out by yourself?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "transportation",
        "target": "function_report",
        "icon": "🚗",
        "question": "How do you usually get around?",
        "helper": "Examples: drive, ride with someone, bus, taxi, rideshare, walk, bicycle, or other.",
        "type": "textarea",
        "check_type": "getting_around",
    },
    {
        "key": "drive",
        "target": "function_report",
        "icon": "🚙",
        "question": "Do you drive?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "drive_details",
        "target": "function_report",
        "icon": "🚙",
        "question": "If you drive, when and how often do you drive?",
        "helper": "Examples: daily, only short trips, only familiar places, or only for appointments.",
        "type": "textarea",
        "depends_on": {"key": "drive", "value": "Yes"},
        "check_type": "getting_around",
    },

    {
        "key": "shopping",
        "target": "function_report",
        "icon": "🛒",
        "question": "Do you shop for groceries, clothing, or other items?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "shopping_details",
        "target": "function_report",
        "icon": "🛍️",
        "question": "What do you shop for, how often, and how long does it take?",
        "helper": "Examples: groceries once a week for one hour, online shopping, or someone shops for me.",
        "type": "textarea",
        "depends_on": {"key": "shopping", "value": "Yes"},
        "check_type": "shopping",
    },

    {
        "key": "pay_bills",
        "target": "function_report",
        "icon": "💵",
        "question": "Can you pay bills, count change, handle a savings account, or use a checkbook or money orders?",
        "helper": "Describe what you can do and any difficulties you have.",
        "type": "textarea",
        "check_type": "money",
    },
    {
        "key": "money_changes",
        "target": "function_report",
        "icon": "💰",
        "question": "Have your conditions changed how you handle money?",
        "helper": "Explain what changed, or write None.",
        "type": "textarea",
        "check_type": "money",
    },
        {
        "key": "hobbies_interests",
        "target": "function_report",
        "icon": "🎨",
        "question": "What hobbies or interests do you have?",
        "helper": "Examples: reading, TV, fishing, video games, crafts, music, sports, gardening, or write None.",
        "type": "textarea",
        "check_type": "hobbies",
    },
    {
        "key": "hobbies_changes",
        "target": "function_report",
        "icon": "🎭",
        "question": "Have your conditions changed your hobbies or interests?",
        "helper": "Explain what changed, or write None.",
        "type": "textarea",
        "check_type": "hobbies",
    },
    {
        "key": "time_with_others",
        "target": "function_report",
        "icon": "👨‍👩‍👧",
        "question": "Do you spend time with other people?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "time_with_others_details",
        "target": "function_report",
        "icon": "🗣️",
        "question": "Who do you spend time with, how often, and what do you do together?",
        "helper": "Examples: family, friends, church, phone calls, meals, or visits.",
        "type": "textarea",
        "depends_on": {
            "key": "time_with_others",
            "value": "Yes"
        },
        "check_type": "social_activities",
    },
    {
        "key": "social_changes",
        "target": "function_report",
        "icon": "🚫",
        "question": "Have your conditions changed your social activities?",
        "helper": "Examples: avoid crowds, don't visit friends, leave early, anxiety, fatigue, or write None.",
        "type": "textarea",
        "check_type": "social_activities",
    },
    {
        "key": "need_accompaniment",
        "target": "function_report",
        "icon": "🤝",
        "question": "Do you need someone to go with you when you go places?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "need_accompaniment_details",
        "target": "function_report",
        "icon": "🚶",
        "question": "Why do you need someone to go with you?",
        "helper": "Examples: safety, memory, anxiety, getting lost, balance, or physical assistance.",
        "type": "textarea",
        "depends_on": {
            "key": "need_accompaniment",
            "value": "Yes"
        },
        "check_type": "social_activities",
    },
    

       {
        "key": "affected_abilities",
        "target": "function_report",
        "icon": "💪",
        "question": "Which activities are harder because of your conditions?",
        "helper": "Select every activity that is affected.",
        "type": "multiselect",
        "options": [
            "Lifting",
            "Squatting",
            "Bending",
            "Standing",
            "Reaching",
            "Walking",
            "Sitting",
            "Kneeling",
            "Stair Climbing",
            "Seeing",
            "Using Hands",
            "Remembering",
            "Completing Tasks",
            "Concentrating",
            "Understanding",
            "Following Instructions",
            "Getting Along With Others",
            "Handling Stress",
            "Handling Changes In Routine",
            "None"
        ],
    },
    {
        "key": "ability_limitations",
        "target": "function_report",
        "icon": "📝",
        "question": "Please explain how these activities are affected.",
        "helper": "Give examples. For example: 'I can only stand for 15 minutes before I need to sit.'",
        "type": "textarea",
        "check_type": "abilities",
    },
    {
        "key": "assistive_devices",
        "target": "function_report",
        "icon": "🦯",
        "question": "Do you use any medical or assistive devices?",
        "helper": "Examples: cane, walker, wheelchair, brace, hearing aid, oxygen, CPAP, splint, or write None.",
        "type": "textarea",
        "check_type": "assistive_devices",
    },
    {
        "key": "assistive_devices_prescribed",
        "target": "function_report",
        "icon": "🏥",
        "question": "Were these devices prescribed by a doctor?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "assistive_devices_details",
        "target": "function_report",
        "icon": "📅",
        "question": "When were the devices prescribed and when do you use them?",
        "helper": "Examples: prescribed in 2022, used every day, only outside the home, or only during flare-ups.",
        "type": "textarea",
        "depends_on": {
            "key": "assistive_devices_prescribed",
            "value": "Yes"
        },
        "check_type": "assistive_devices",
    },
    {
        "key": "medication_side_effects",
        "target": "function_report",
        "icon": "💊",
        "question": "Do your medications cause any side effects?",
        "helper": "Examples: drowsiness, dizziness, nausea, headaches, memory problems, or write None.",
        "type": "textarea",
        "check_type": "medication_side_effects",
    },
    {
        "key": "function_report_remarks",
        "target": "function_report",
        "icon": "📌",
        "question": "Is there anything else you want Social Security to know about your daily limitations?",
        "helper": "Include anything important that hasn't already been discussed.",
        "type": "textarea",
        "check_type": "function_report_remarks",
    },
]
