FUNCTION_REPORT_QUESTIONS = [
    {
        "key": "function_name",
        "target": "function_report",
        "icon": "👤",
        "question": "What is your full name?",
        "helper": "Enter the name of the disabled person.",
        "type": "text",
    },
    {
        "key": "function_ssn",
        "target": "function_report",
        "icon": "🔢",
        "question": "What is your Social Security number?",
        "helper": "You can leave this blank and add it later if needed.",
        "type": "text",
    },
    {
        "key": "function_phone",
        "target": "function_report",
        "icon": "📞",
        "question": "What daytime phone number can Social Security use to reach you?",
        "helper": "Include area code. If none, write None.",
        "type": "text",
    },
    {
        "key": "living_place",
        "target": "function_report",
        "icon": "🏠",
        "question": "Where do you live?",
        "helper": "Choose the closest option.",
        "type": "select",
        "options": ["", "House", "Apartment", "Boarding House", "Nursing Home", "Shelter", "Group Home", "Other"],
    },
    {
        "key": "living_with",
        "target": "function_report",
        "icon": "👥",
        "question": "Who do you live with?",
        "helper": "Choose the closest option.",
        "type": "select",
        "options": ["", "Alone", "With Family", "With Friends", "Other"],
    },
    {
        "key": "condition_limits_work",
        "target": "function_report",
        "icon": "🩺",
        "question": "How do your illnesses, injuries, or conditions limit your ability to work?",
        "helper": "Describe how your conditions affect work tasks, attendance, pain, focus, movement, or stamina.",
        "type": "textarea",
    },
    {
        "key": "daily_routine",
        "target": "function_report",
        "icon": "🌅",
        "question": "What do you do from the time you wake up until going to bed?",
        "helper": "Describe a typical day. Include meals, chores, rest breaks, help from others, and activities you avoid.",
        "type": "textarea",
    },
    {
        "key": "care_for_others",
        "target": "function_report",
        "icon": "🤝",
        "question": "Do you take care of anyone else?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "care_for_others_details",
        "target": "function_report",
        "icon": "🤝",
        "question": "Who do you care for, and what do you do for them?",
        "helper": "Only answer this if you said Yes.",
        "type": "textarea",
        "depends_on": {"key": "care_for_others", "value": "Yes"},
    },
    {
        "key": "care_for_pets",
        "target": "function_report",
        "icon": "🐾",
        "question": "Do you take care of pets or other animals?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "care_for_pets_details",
        "target": "function_report",
        "icon": "🐾",
        "question": "What do you do for the pets or animals?",
        "helper": "Only answer this if you said Yes.",
        "type": "textarea",
        "depends_on": {"key": "care_for_pets", "value": "Yes"},
    },
    {
        "key": "help_care_others_animals",
        "target": "function_report",
        "icon": "🧑‍🤝‍🧑",
        "question": "Does anyone help you care for other people or animals?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "help_care_others_animals_details",
        "target": "function_report",
        "icon": "🧑‍🤝‍🧑",
        "question": "Who helps, and what do they do to help?",
        "helper": "Only answer this if you said Yes.",
        "type": "textarea",
        "depends_on": {"key": "help_care_others_animals", "value": "Yes"},
    },
    {
        "key": "before_conditions",
        "target": "function_report",
        "icon": "🔙",
        "question": "What could you do before your conditions that you cannot do now?",
        "helper": "Examples: work, lift, stand, drive, cook, clean, shop, socialize, concentrate.",
        "type": "textarea",
    },
    {
        "key": "sleep_affected",
        "target": "function_report",
        "icon": "🌙",
        "question": "Do your conditions affect your sleep?",
        "helper": "Choose Yes or No.",
        "type": "radio",
        "options": ["No", "Yes"],
    },
    {
        "key": "sleep_affected_details",
        "target": "function_report",
        "icon": "🌙",
        "question": "How do your conditions affect your sleep?",
        "helper": "Examples: pain wakes you up, trouble falling asleep, medication side effects, nightmares, or needing naps.",
        "type": "textarea",
        "depends_on": {"key": "sleep_affected", "value": "Yes"},
    },
]